### ISSUE TITLE
Review SQL Code & Tests

### ISSUE THREAD

**Issue by matthewjohnpayne** [matthewjohnpayne/cheby_checker#12]

**Comment by matthewjohnpayne** [comment]
MJP's first issues created via Zenhub. 

MJP believes that he has written & tested most of the relevant code for the sql.py, including the "cheby_checker.py" module which sql.py imports.

Someone (Jan!) should get to grips with the code, perform independent checks of import, tests, etc. 

Next step is for MJP to learn how to assign Jan to this task ...

**Comment by jankansky** [comment]
test_sql.py and test_cheby_checker.py are passing in my code. I will continue to dig into those modules to understand the structure.
