### ISSUE TITLE
mpcpp missing

### ISSUE THREAD

**Issue by jankansky** [matthewjohnpayne/cheby_checker#14]
A lot of code tries to do import mpcpp.MPC_library as mpc, but the module is not found

**Comment by matthewjohnpayne** [comment]
Partial solution implemented:
 - MPC_library.py directly added to cheby_checker

Remaining work:
 - Need to update dependent modules (e.g. nbody.py) to import MPC_library from the local version (in cheby) rather than from mpcpp.MPC_library

**Comment by matthewjohnpayne** [comment]
Full (?) solution implemented:
 - Import of MPC_library changed to local version (in cheby_checker) rather than external mpcpp library
