### ISSUE TITLE
mpc_nbody moved to archaic folder

### ISSUE THREAD

**Issue by jankansky** [matthewjohnpayne/cheby_checker#15]
I believe that mpc_nbody is now in the archaic folder and nbody.py takes the place of that code.  However imports in other code haven't been changed to handle this.

**Comment by matthewjohnpayne** [comment]
(1) Interpretation correct
 - nbody.py takes the place of mpc_nbody.py 

(2) Code imports have now been updated by MJP: 
 - Updated import statements, code-executions and comments have been put in place in the following modules:
 - nbody.py
 - precalc.py
 - orbit_cheby.py
